version: '3'

services:
  sidecar-service:
    image: finuras/sidecar-service
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '~/.config/finuras/sidecar:/.config/finuras/sidecar'
    environment:
      SSL_MODE: 'off'
    ports:
      - '5678:80'
