# For more information: https://laravel.com/docs/sail
version: '3'

services:
  sidecar:
    build:
      context: .
      dockerfile: ./docker/extension/Dockerfile
    image: finuras/sidecar-service
    volumes:
      - '.:/var/www/html'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '~/.config/finuras/sidecar:/var/www/html/storage/app/sidecar'
    environment:
      SSL_MODE: 'off'
    ports:
      - '${APP_PORT:-80}:80'
