# For more information: https://laravel.com/docs/sail
version: '3'

networks:
  raft:
    driver: bridge

x-raft-base: &raft-base
  build:
    context: .
    dockerfile: ./docker/ssu/Dockerfile
  image: finuras/raft-server:ssu-with-docker-cli
  volumes:
    - '.:/var/www/html'
  networks:
    - raft

services:
  raft:
    <<: *raft-base
    environment:
      SSL_MODE: 'off'
      PHP_POOL_NAME: "raft-www"
    ports:
      - '${APP_PORT:-80}:80'
  raft-queue:
    <<: *raft-base
    volumes:
      - '.:/var/www/html'
      - '~/.config/finuras/raft:/.config/finuras/raft'
      - '/var/run/docker.sock:/var/run/docker.sock'
    command: [ "su", "webuser", "-c", "php artisan queue:work --tries=3" ]
    environment:
      SSL_MODE: 'off'
      PHP_POOL_NAME: "raft-queue"
