# For more information: https://laravel.com/docs/sail
version: '3'
services:
    raft:
        build:
            context: .
            dockerfile: ./docker/ssu/Dockerfile
        image: finuras/raft-server:ssu-with-docker-cli
        environment:
          PHP_POOL_NAME: "raft-server"
          PHP_DISPLAY_STARTUP_ERRORS: 'on'
          SSL_MODE: 'off'
          AUTORUN_LARAVEL_STORAGE_LINK: 'off'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        volumes:
            - '.:/var/www/html'
            - '~/.config/finuras/raft:/.config/finuras/raft'
            - '/var/run/docker.sock:/var/run/docker.sock'
        networks:
            - sail
networks:
    sail:
        driver: bridge
